improve argument handling and add version bumping feature

diff --git a/change b/change
--- a/change
+++ b/change
@@ -9,32 +9,34 @@ nl="
 "
 
 Usage() {
-    echo "usage: change [COMMAND]"
+    echo "usage: change [COMMAND [ARGS]]"
     echo
     echo "change"
     echo "    updates an existing $change_file"
     echo
-    echo "change tag [-p]"
+    echo "change init"
+    echo "    creates a $change_file with the first version"
+    echo
+    echo "change tag [-p] [--bump PATH]"
     echo "    tags the latest local commit with the lastest $change_file version"
     echo "    optional: -p also pushes that tag to origin"
+    echo "    optional: --bump passes the latest version as an arg to a script at PATH"
+    echo
+    echo "change auth [--token TOKEN]"
+    echo "    prompts you for a personal access token for posting releases"
+    echo "    optional: --token uses TOKEN instead of asking for it interactively"
     echo
     echo "change post [--dry-run]"
     echo "    posts a GitHub release for the latest version in $change_file"
     echo "    optional: --dry-run prints url, version, and body without sending"
     echo
-    echo "change auth [TOKEN]"
-    echo "    prompts you for a personal access token for posting releases"
-    echo "    optional: give token as argument instead of with prompt"
-    echo
-    echo "change init"
-    echo "    creates a $change_file with the first version"
-    echo
-    echo "change all"
+    echo "change all [--bump PATH]"
     echo "    runs change, then opens $change_file in \$EDITOR"
     echo "    commits and pushes the $change_file to origin"
     echo "    runs change tag -p and then runs change post"
+    echo "    optional: --bump passes the new version as an arg to an executable at PATH"
     echo
-    echo "change --version"
+    echo "change version"
     echo "    prints which version of the change tool is being used"
 }
 
@@ -259,17 +261,21 @@ startup_checks() {
 #### Public ####
 
 Make_and_push_tag() {
-    push_tag=$1 # send arg "-p" to push tag
-    [ "$push_tag" ] && [ "$push_tag" != -p ] &&
-        { echo "$push_tag is not a valid argument" >&2; return 1; }
-
     ! startup_checks && return 1
     latest_log_tag=$(sed -n "s|^\[Unreleased\]:.*/\(.*\)\.\.\.HEAD$|\1|p" $change_file)
 
     git tag "$latest_log_tag" || return 1
     echo "tagged latest commit as $latest_log_tag"
 
-    [ "$push_tag" = -p ] &&
+    [ -x "$bump_script" ] &&
+        echo "executing $bump_script $latest_log_tag" &&
+        "$bump_script" "$latest_log_tag"
+
+    [ ! -x "$bump_script" ] && [ -f "$bump_script" ] &&
+        echo "executing sh $bump_script $latest_log_tag" &&
+        sh "$bump_script" "$latest_log_tag"
+
+    [ "$push_tag" = "true" ] &&
         git push --quiet origin "$latest_log_tag" &&
         echo "pushed $latest_log_tag to origin" &&
         return 0
@@ -279,8 +285,6 @@ Make_and_push_tag() {
 }
 
 Save_auth() {
-    token=$1
-
     [ ! "$token" ] && echo "enter a personal access token" && printf "token: " && read -r token
     [ ! "$token" ] && { echo "invalid token" >&2; return 1; }
     [ ! -d "$auth_dir" ] && mkdir -p "$auth_dir"
@@ -289,10 +293,6 @@ Save_auth() {
 }
 
 Post_release() {
-    dry_run=$1 # send arg "--dry-run" to print but not send the POST request
-    [ "$dry_run" ] && [ "$dry_run" != --dry-run ] &&
-        { echo "$dry_run is not a valid argument" >&2; return 1; }
-
     ! startup_checks && return 1
     [ ! -e "$auth_file" ] && { echo "you need to save a token with the auth" >&2; return 1; }
 
@@ -305,7 +305,7 @@ Post_release() {
     link=$(grep "^\[$latest_log_ver\]: .*" $change_file)
     body=$(echo "$diff$nl$nl$link" | sed -e "s|\([\"\\]\)|\\\\\1|g" -e "s|$|\\\\|" | tr '\n' 'n')
 
-    [ "$dry_run" = --dry-run ] &&
+    [ "$dry_run" = "true" ] &&
         printf "%s\n%s\n%s\n" "$repo_url" "$latest_log_tag" "$body" && return 0
 
     curl -X POST "$repo_url/releases" \
@@ -378,24 +378,43 @@ Run_all() {
         echo "cancelling because no manual edits were made to $change_file" >&2 &&
         echo "$save_file" > $change_file &&
         return 1
+    push_tag="true"
     git add $change_file &&
         git commit --quiet -m "docs: update changelog" &&
         git push --quiet origin &&
-        Make_and_push_tag -p && Post_release
+        Make_and_push_tag && Post_release
 }
 
 #### Args ####
 
-[ ! "$1"             ] && { Update_changelog;             exit;   }
-[ "$3"               ] && { echo "too many argument" >&2; exit 1; }
-[ "$1" = "auth"      ] && { Save_auth "$2";               exit;   }
-[ "$1" = "post"      ] && { Post_release "$2";            exit;   }
-[ "$1" = "tag"       ] && { Make_and_push_tag "$2";       exit;   }
-[ "$2"               ] && { echo "too many argument" >&2; exit 1; }
-[ "$1" = "init"      ] && { Create_changelog;             exit;   }
-[ "$1" = "all"       ] && { Run_all;                      exit;   }
-[ "$1" = "-h"        ] && { Usage;                        exit;   }
-[ "$1" = "help"      ] && { Usage;                        exit;   }
-[ "$1" = "--help"    ] && { Usage;                        exit;   }
-[ "$1" = "--version" ] && { echo "$change_version";       exit;   }
-[ "$1" ] && { printf "couldn't recognize argument\n\n" >&2; Usage >&2; exit 1; }
+command=$1
+shift
+
+while [ $# != 0 ]; do
+    case $1 in
+        "-p" ) push_tag="true";;
+        "--dry-run" ) dry_run="true";;
+        "--bump" ) bump_script="$2"; shift;;
+        "--bump="* ) bump_script="${1#*=}";;
+        "--token" ) token="$2"; shift;;
+        "--token="* ) token="${1#*=}";;
+        * ) echo "invalid argument: $1" >&2; exit 1;;
+    esac
+
+    shift
+done
+
+
+case $command in
+    "" ) Update_changelog;;
+    "init" ) Create_changelog;;
+    "auth" ) Save_auth;;
+    "tag"  ) Make_and_push_tag;;
+    "post" ) Post_release;;
+    "all"  ) Run_all;;
+    "help" | "--help" | "-h" ) Usage;;
+    "version" | "--version" | "-v" ) echo "$change_version";;
+    * ) echo "invalid command: $command" >&2; exit 1;;
+esac
+
+exit
