fix: improve curl options and error handling

diff --git a/change b/change
--- a/change
+++ b/change
@@ -166,10 +166,14 @@ post_release() {
 "
     body=$(echo "$diff$nl$nl$link" | sed "s|$|\\\\|" | tr '\n' 'n')
 
-    curl -X POST "$repo_url/releases" \
+    curl -X POST "$repo_url/releases" --silent \
         -u "$(git config --get user.email)" \
         -H "Content-Type: application/json" \
-        -d "{\"tag_name\": \"$latest_log_ver_name\", \"name\": \"$latest_log_ver_name\", \"body\": \"$body\" }"
+        -d "{\"tag_name\": \"$latest_log_ver_name\", \"name\": \"$latest_log_ver_name\", \"body\": \"$body\" }" &&
+        echo "posted release for $latest_git_ver_name" && exit
+
+    echo "error in posting release for $latest_git_ver_name"
+    exit 1
 }
 
 init() {
@@ -203,11 +207,12 @@ $(format_commits "$first_commits")
 #### Start ####
 
 [ "$2" ] && { echo "change currently accepts only one argument" >&2; exit 1; }
+[ "$1" = "init" ] && { init; exit; }
+[ "$1" = "release" ] && { post_release; exit; }
 [ "$1" = "-h" ] && { usage; exit; }
 [ "$1" = "help" ] && { usage; exit; }
 [ "$1" = "--help" ] && { usage; exit; }
-[ "$1" = "init" ] && { init; exit; }
-[ "$1" = "release" ] && { post_release; exit; }
+[ "$1" ] && { printf "couldn't recognize argument\n\n" >&2; usage >&2; exit 1; }
 
 [ ! -e "$change_file" ] && { echo "couldn't find $change_file" >&2; exit 1; }
 
