refactor: improve naming, layout, readability, and functions

diff --git a/change b/change
--- a/change
+++ b/change
@@ -8,7 +8,7 @@ change_version="0.12.0"
 nl="
 "
 
-usage() {
+Usage() {
     echo "usage: change [COMMAND]"
     echo
     echo "change"
@@ -38,147 +38,202 @@ usage() {
     echo "    prints which version of the change tool is being used"
 }
 
-get_versions() {
-    reverse=${1:-v} # sending arg "-v" reverses the list
+#### Tags ####
+
+get_git_tags() {
+    reverse=${1:-v} # send arg "-v" to reverse the list
     git tag --list "[0-9]*\.[0-9]*.*" "v[0-9]*\.[0-9]*.*" --sort="${reverse}:refname"
 }
 
-rm_ver_prefix() {
-    echo "$1" | sed "s|^[^0-9]*\([0-9.]*.*\)|\1|"
-}
-
-rm_ver_suffix() {
-    sed "s|\(^[^0-9]*[0-9.]*\).*|\1|"
-}
-
-get_ver_name_date() {
-    date=$(git log -1 --pretty=format:"%ci" "$1" 2> /dev/null | cut -d " " -f 1)
+get_tag_date() {
+    date=$(git log -1 --pretty=format:"%ci" "$1" 2>/dev/null | cut -d " " -f 1)
     [ "$date" ] && { echo "$date"; return; }
     date +%F
 }
 
-fmt_subject() {
-    rm_prefix=$(echo "$1" | sed -e "s|^[^ ]*(\(.*\))!*: \(.*$\)|\2 for \1|" -e "s|^[^ ]*: \(.*$\)|\1|")
-
-    IFS="$nl"
-    for subject in $rm_prefix; do
-        first_char=$(echo "$subject" | cut -c 1 | tr "[:lower:]" "[:upper:]")
-
-        echo "$subject" | sed -e "s|^.\(.*$\)|$first_char\1|" -e "s|\(.*\)|- \1.|"
-    done
+rm_tag_prefix() {
+    echo "$1" | sed "s|^[^0-9]*\([0-9.]*.*\)|\1|"
 }
 
-format_commits() {
-    list="$1"
-
-    dep=$(echo "$list" | grep "^[^ ]*!: ")
-    list=$(echo "$list" | grep -v "^[^ ]*!: ")
-
-    feat=$(echo "$list" | grep -i "^feat: \|^feat(.*): ")
-    list=$(echo "$list" | grep -iv "^feat: \|^feat(.*): ")
-
-    fix=$(echo "$list" | grep -i "^fix: \|^fix(.*): ")
-    list=$(echo "$list" | grep -iv "^fix: \|^fix(.*): ")
-
-    [ "$dep" ] && echo "### Deprecated" && fmt_subject "$dep" && echo ""
-    [ "$feat" ] && echo "### Added" && fmt_subject "$feat" && echo ""
-    [ "$fix" ] && echo "### Fixed" && fmt_subject "$fix" && echo ""
-    [ "$list" ] && echo "### Changed" && fmt_subject "$list" && echo ""
-}
-
-increment_major() {
+inc_tag_major() {
     cur_major=$(echo "$1" | sed "s|^[^0-9]*\([0-9]*\)\..*$|\1|")
     echo "$1" | sed "s|\.[0-9]*|.0|g" |
         sed "s|\(^[^0-9]*\)[0-9]*\(\..*$\)|\1$(( cur_major + 1 ))\2|"
 }
 
-increment_minor() {
+inc_tag_minor() {
     cur_minor=$(echo "$1" | sed "s|^.*\.\([0-9]*\)\..*$|\1|")
     echo "$1" | sed "s|\.[0-9]*|.0|g" |
         sed "s|\(^.*\.\)[0-9]*\(\..*$\)|\1$(( cur_minor + 1 ))\2|"
 }
 
-increment_patch() {
+inc_tag_patch() {
     cur_patch=$(echo "$1" | sed "s|^.*\.\([0-9]*\).*$|\1|")
     echo "$1" | sed "s|\(^.*\.\)[0-9]*\(.*$\)|\1$(( cur_patch + 1 ))\2|"
 }
 
-get_new_version_name() {
-    latest_changes=$1
-    latest_git_ver_name=$2
-
-    echo "$latest_changes" | grep -q ".!: \|^BREAKING.CHANGE: " &&
-        increment_major "$latest_git_ver_name" && return
-
-    echo "$latest_changes" | grep -iq "^feat: \|^feat(.*): " &&
-        increment_minor "$latest_git_ver_name" && return
-
-    echo "$latest_changes" | grep -iq "^fix: \|^fix(.*): " &&
-        increment_patch "$latest_git_ver_name" && return
+rm_tag_suffix() {
+    sed "s|\(^[^0-9]*[0-9.]*\).*|\1|"
 }
 
-get_needed_log_ver_names() {
-    latest_git_ver_name=$1
-    latest_log_ver_name=$2
+#### Commits ####
 
-    tags=$(get_versions -v)
+filter_major_commits() {
+    args="-e" # send arg "-v" for inverse and "-q" for quiet
+    [ "$1" ] && args="${1}e"
 
-    ! echo "$tags" | grep -q "$latest_log_ver_name" && return 0
-    echo "$tags" | sed -n "/$latest_log_ver_name/!p;//q" | sed '1!G;h;$!d'
-
-    latest_changes=$(git log --pretty=format:"%B" "$latest_git_ver_name..")
-    [ ! "$latest_changes" ] && return
-
-    get_new_version_name "$latest_changes" "$latest_git_ver_name" | rm_ver_suffix
+    grep "$args" "^[A-z]*!: " \
+        -e "^[A-z]*(.*)!: " \
+        -e "^[*-] *[A-z]*!: " \
+        -e "^[*-] *[A-z]*(.*)!: " \
+        -e "^BREAKING[ -]CHANGE: " \
+        -e "^[*-] *BREAKING[ -]CHANGE: " \
+        -e "^BREAKING[ -]CHANGE"
 }
 
-update_diffs() {
-    latest_git_ver_name=$1
-    latest_log_ver_name=$2
-    needed_log_ver_name=$3
+filter_minor_commits() {
+    args="-e" # send arg "-v" for inverse and "-q" for quiet
+    [ "$1" ] && args="${1}e"
 
-    latest_log_ver=$(rm_ver_prefix "$latest_log_ver_name")
-    needed_log_ver=$(rm_ver_prefix "$needed_log_ver_name")
-    new_commits=$(get_commits_between "$latest_git_ver_name" \
-        "$latest_log_ver_name" "$needed_log_ver_name")
-
-    new_section="## [$needed_log_ver] - $(get_ver_name_date "$needed_log_ver_name")\\
-$(format_commits "$new_commits" | sed -e "s|\([&\\]\)|\\\\\1|g" -e "s|$|\\\\|")"
-
-    sed -i.backup "s|\(^## \[$latest_log_ver\] -.*$\)|$new_section$nl\1|" $change_file &&
-        rm "${change_file}.backup"
+    grep -i "$args" "^feat: " \
+        -e "^feat(.*): " \
+        -e "^[*-] *feat: " \
+        -e "^[*-] *feat(.*): "
 }
 
-update_links() {
-    latest_log_ver_name=$1
-    needed_log_ver_name=$2
+filter_patch_commits() {
+    args="-e" # send arg "-v" for inverse and "-q" for quiet
+    [ "$1" ] && args="${1}e"
 
-    latest_log_ver=$(rm_ver_prefix "$latest_log_ver_name")
-    needed_log_ver=$(rm_ver_prefix "$needed_log_ver_name")
-    repo_url=$(git config --get remote.origin.url | sed "s|\(.*\)\.git|\1|")
+    grep -i "$args" "^fix: " \
+        -e "^fix(.*): " \
+        -e "^[*-] *fix: "\
+        -e "^[*-] *fix(.*): "
+}
 
-    new_link="[$needed_log_ver]: $repo_url/compare/$latest_log_ver_name...$needed_log_ver_name"
+filter_conv_commits() {
+    grep -e "^[A-z]*: " -e "^[A-z]*(.*): " \
+        -e "^[*-] *[A-z]*: " -e "^[*-] *[A-z]*(.*): " \
+        -e "^[A-z]*!: " -e "^[A-z]*(.*)!: " \
+        -e "^[*-] *[A-z]*!: " -e "^[*-] *[A-z]*(.*)!: " \
+        -e "^BREAKING[ -]CHANGE: " -e "^[*-] *BREAKING[ -]CHANGE: " \
+        -e "^BREAKING[ -]CHANGE"
+}
 
-    sed -i.backup "s|\(^\[$latest_log_ver\]:.*$\)|$new_link\\$nl\1|" "$change_file" &&
-        rm "${change_file}.backup"
+fmt_conv_type() {
+    sed -e "s|^[A-z]*: \(.*$\)|\1|g" \
+        -e "s|^[A-z]*(\(.*\)): \(.*$\)|\2 for \1|g" \
+        -e "s|^[*-] *[A-z]*: \(.*$\)|\1|g" \
+        -e "s|^[*-] *[A-z]*(\(.*\)): \(.*$\)|\2 for \1|g" \
+        -e "s|^[A-z]*!: \(.*$\)|\1|g" \
+        -e "s|^[A-z]*(\(.*\))!: \(.*$\)|\2 for \1|g" \
+        -e "s|^[*-] *[A-z]*!: \(.*$\)|\1|g" \
+        -e "s|^[*-] *[A-z]*(\(.*\))!: \(.*$\)|\2 for \1|g" \
+        -e "s|^BREAKING[ -]CHANGE: \(.*$\)|\1|g" \
+        -e "s|^[*-] *BREAKING[ -]CHANGE: \(.*$\)|\1|g" \
+        -e "s|^BREAKING[ -]CHANGE|a breaking change|g"
+}
 
-    reg="s|\(^\[Unreleased\]:.*\)/$latest_log_ver_name\.\.\.HEAD$|\1/$needed_log_ver_name...HEAD|"
-    sed -i.backup "$reg" "$change_file" &&
-        rm "${change_file}.backup"
+fmt_commits() {
+    all_commits=$(echo "$1" | fmt_conv_type)
+
+    IFS="$nl"
+    for commit in $all_commits; do
+        first_char=$(echo "$commit" | cut -c 1 | tr "[:lower:]" "[:upper:]")
+
+        echo "$commit" | sed -e "s|^.\(.*$\)|- $first_char\1.|"
+    done
 }
 
 get_commits_between() {
-    latest_git_ver_name=$1
-    latest_log_ver_name=$2
-    needed_log_ver_name=$3
+    latest_git_tag=$1
+    latest_log_tag=$2
+    needed_tag=$3
 
-    highest_ver_name=$(printf "%s\n%s\n" "$latest_git_ver_name" "$needed_log_ver_name" |
+    highest_tag=$(printf "%s\n%s\n" "$latest_git_tag" "$needed_tag" |
         sort -Vr | head -1)
 
-    [ "$latest_git_ver_name" = "$highest_ver_name" ] &&
-        git log --pretty=format:"%s" "$latest_log_ver_name..$needed_log_ver_name" && return
+    tag_range="$latest_log_tag.."
+    [ "$latest_git_tag" = "$highest_tag" ] && tag_range="$latest_log_tag..$needed_tag"
+    git log --pretty=format:"%s%n%b" "$tag_range"
+}
 
-    git log --pretty=format:"%s" "$latest_log_ver_name.."
+#### Utils ####
+
+get_new_tag() {
+    latest_changes=$1
+    latest_git_tag=$2
+
+    echo "$latest_changes" | filter_major_commits -q && inc_tag_major "$latest_git_tag" && return
+    echo "$latest_changes" | filter_minor_commits -q && inc_tag_minor "$latest_git_tag" && return
+    echo "$latest_changes" | filter_patch_commits -q && inc_tag_patch "$latest_git_tag" && return
+}
+
+format_commits() {
+    list="$1"
+    list=$(echo "$list" | filter_conv_commits)
+
+    dep=$(echo "$list" | filter_major_commits)
+    list=$(echo "$list" | filter_major_commits -v)
+
+    feat=$(echo "$list" | filter_minor_commits)
+    list=$(echo "$list" | filter_minor_commits -v)
+
+    fix=$(echo "$list" | filter_patch_commits)
+    list=$(echo "$list" | filter_patch_commits -v)
+
+    [ "$dep" ] && echo "### BREAKING CHANGE" && fmt_commits "$dep" && echo
+    [ "$feat" ] && echo "### Added" && fmt_commits "$feat" && echo
+    [ "$fix" ] && echo "### Fixed" && fmt_commits "$fix" && echo
+    [ "$list" ] && echo "### Changed" && fmt_commits "$list" && echo
+}
+
+get_needed_tags() {
+    latest_git_tag=$1
+    latest_log_tag=$2
+
+    tags=$(get_git_tags -v)
+
+    ! echo "$tags" | grep -q "$latest_log_tag" && return 0
+    echo "$tags" | sed -n "/$latest_log_tag/!p;//q" | sed '1!G;h;$!d'
+
+    latest_changes=$(git log --pretty=format:"%B" "$latest_git_tag..")
+    [ ! "$latest_changes" ] && return
+
+    get_new_tag "$latest_changes" "$latest_git_tag" | rm_tag_suffix
+}
+
+update_diffs() {
+    latest_git_tag=$1
+    latest_log_tag=$2
+    needed_tag=$3
+
+    latest_log_ver=$(rm_tag_prefix "$latest_log_tag")
+    needed_ver=$(rm_tag_prefix "$needed_tag")
+    new_commits=$(get_commits_between "$latest_git_tag" "$latest_log_tag" "$needed_tag")
+
+    new_section="## [$needed_ver] - $(get_tag_date "$needed_tag")\\
+$(format_commits "$new_commits" | sed -e "s|\([&\\]\)|\\\\\1|g" -e "s|$|\\\\|")"
+
+    regex="s|\(^## \[$latest_log_ver\] -.*$\)|$new_section$nl\1|"
+    sed -i.backup "$regex" $change_file && rm "${change_file}.backup"
+}
+
+update_links() {
+    latest_log_tag=$1
+    needed_tag=$2
+
+    latest_log_ver=$(rm_tag_prefix "$latest_log_tag")
+    needed_ver=$(rm_tag_prefix "$needed_tag")
+    repo_url=$(git config --get remote.origin.url | sed "s|\(.*\)\.git|\1|")
+
+    new_link="[$needed_ver]: $repo_url/compare/$latest_log_tag...$needed_tag"
+
+    regex="s|\(^\[$latest_log_ver\]:.*$\)|$new_link\\$nl\1|"
+    sed -i.backup "$regex" "$change_file" && rm "${change_file}.backup"
+
+    regex="s|\(^\[Unreleased\]:.*\)/$latest_log_tag\.\.\.HEAD$|\1/$needed_tag...HEAD|"
+    sed -i.backup "$regex" "$change_file" && rm "${change_file}.backup"
 }
 
 startup_checks() {
@@ -186,50 +241,53 @@ startup_checks() {
     [ ! -d .git ] && { echo "the current directory doesn't contain .git" >&2; return 1; }
     ! git config --get remote.origin.url >/dev/null &&
         { echo "remote origin url isn't set for this repo" >&2; return 1; }
+
     return 0
 }
 
-make_and_push_tag() {
-    push_tag=$1 # sending arg "-p" pushes
-    [ "$push_tag" ] && [ "$push_tag" != -p ] && { echo "$push_tag is not a valid argument" >&2; return 1; }
+#### Public ####
+
+Make_and_push_tag() {
+    push_tag=$1 # send arg "-p" to push tag
+    [ "$push_tag" ] && [ "$push_tag" != -p ] &&
+        { echo "$push_tag is not a valid argument" >&2; return 1; }
 
     ! startup_checks && return 1
-    latest_log_ver_name=$(sed -n "s|^\[Unreleased\]:.*/\(.*\)\.\.\.HEAD$|\1|p" $change_file)
+    latest_log_tag=$(sed -n "s|^\[Unreleased\]:.*/\(.*\)\.\.\.HEAD$|\1|p" $change_file)
 
-    git tag "$latest_log_ver_name" || return 1
-    echo "tagged latest commit as $latest_log_ver_name"
+    git tag "$latest_log_tag" || return 1
+    echo "tagged latest commit as $latest_log_tag"
 
     [ "$push_tag" = -p ] &&
-        git push --quiet origin "$latest_log_ver_name" &&
-        echo "pushed $latest_log_ver_name to origin" &&
+        git push --quiet origin "$latest_log_tag" &&
+        echo "pushed $latest_log_tag to origin" &&
         return 0
 
-    echo "to push the latest tag use: git push origin $latest_log_ver_name"
+    echo "to push the latest tag use: git push origin $latest_log_tag"
     echo "to push all local tags use: git push origin --tags"
 }
 
-auth() {
+Save_auth() {
     token=$1
-    [ ! "$token" ] &&
-        echo "enter a personal access token" &&
-        printf "token: " &&
-        read -r token
 
+    [ ! "$token" ] && echo "enter a personal access token" && printf "token: " && read -r token
     [ ! "$token" ] && { echo "invalid token" >&2; return 1; }
     [ ! -d "$auth_dir" ] && mkdir -p "$auth_dir"
+
     echo "$token" | base64 > "$auth_file" && echo "git auth saved"
 }
 
-post_release() {
-    dry_run=$1 # sending arg "--dry-run" will print but not send a POST request
-    [ "$dry_run" ] && [ "$dry_run" != --dry-run ] && { echo "$dry_run is not a valid argument" >&2; return 1; }
+Post_release() {
+    dry_run=$1 # send arg "--dry-run" to print but not send the POST request
+    [ "$dry_run" ] && [ "$dry_run" != --dry-run ] &&
+        { echo "$dry_run is not a valid argument" >&2; return 1; }
 
     ! startup_checks && return 1
     [ ! -e "$auth_file" ] && { echo "you need to save a token with the auth" >&2; return 1; }
 
     auth_token=$(base64 --decode < "$auth_file")
-    latest_log_ver_name=$(sed -n "s|^\[Unreleased\]:.*/\(.*\)\.\.\.HEAD$|\1|p" $change_file)
-    latest_log_ver=$(rm_ver_prefix "$latest_log_ver_name")
+    latest_log_tag=$(sed -n "s|^\[Unreleased\]:.*/\(.*\)\.\.\.HEAD$|\1|p" $change_file)
+    latest_log_ver=$(rm_tag_prefix "$latest_log_tag")
 
     repo_url=$(git config --get remote.origin.url |
         sed -e "s|\(.*\)\.git|\1|" -e "s|\(^.*\)\(github.com\)|\1api.\2/repos|")
@@ -238,25 +296,26 @@ post_release() {
     link=$(grep "^\[$latest_log_ver\]: .*" $change_file)
     body=$(echo "$diff$nl$nl$link" | sed -e "s|\([\"\\]\)|\\\\\1|g" -e "s|$|\\\\|" | tr '\n' 'n')
 
-    [ "$dry_run" = --dry-run ] && printf "%s\n%s\n%s\n" "$repo_url" "$latest_log_ver_name" "$body" && return 0
+    [ "$dry_run" = --dry-run ] &&
+        printf "%s\n%s\n%s\n" "$repo_url" "$latest_log_tag" "$body" && return 0
 
     curl -X POST "$repo_url/releases" \
         -H "Authorization: token $auth_token" \
         -H "Content-Type: application/json" \
-        -d "{\"tag_name\": \"$latest_log_ver_name\", \"name\": \"$latest_log_ver_name\", \"body\": \"$body\" }"
+        -d "{\"tag_name\": \"$latest_log_tag\", \"name\": \"$latest_log_tag\", \"body\": \"$body\" }"
 }
 
-init() {
+Create_changelog() {
     [ ! -d .git ] && { echo "the current directory doesn't contain .git" >&2; return 1; }
     [ -e "$change_file" ] && { echo "$change_file already exists" >&2; return 1; }
 
-    first_ver_name=$(get_versions | head -1)
-    [ ! "$first_ver_name" ] && { echo "couldn't find any valid version tags" >&2; return 2; }
+    first_tag=$(get_git_tags | head -1)
+    [ ! "$first_tag" ] && { echo "couldn't find any valid version tags" >&2; return 2; }
 
-    first_ver=$(rm_ver_prefix "$first_ver_name")
+    first_ver=$(rm_tag_prefix "$first_tag")
     [ ! "$first_ver" ] && { echo "couldn't get first version" >&2; return 2; }
 
-    first_commits=$(git log --pretty=format:"%s" "$first_ver_name")
+    first_commits=$(git log --pretty=format:"%s" "$first_tag")
     [ ! "$first_commits" ] && { echo "couldn't get first commits" >&2; return 2; }
 
     repo_url=$(git config --get remote.origin.url | sed "s|\(.*\)\.git|\1|")
@@ -270,20 +329,39 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ## [Unreleased]
 
-## [$first_ver] - $(get_ver_name_date "$first_ver_name")
+## [$first_ver] - $(get_tag_date "$first_tag")
 $(format_commits "$first_commits")
 
-[Unreleased]: $repo_url/compare/$first_ver_name...HEAD
-[$first_ver]: $repo_url/releases/tag/$first_ver_name" > "$change_file"
+[Unreleased]: $repo_url/compare/$first_tag...HEAD
+[$first_ver]: $repo_url/releases/tag/$first_tag" > "$change_file"
 
     [ ! -e "$change_file" ] &&
         echo "something when wrong while creating $change_file" >&2 && return 1
     echo "created $change_file"
 }
 
-run_all() {
+Update_changelog() {
+    ! startup_checks && return 1
+
+    latest_git_tag=$(get_git_tags -v | head -1)
+    latest_log_tag=$(sed -n "s|^\[Unreleased\]:.*/\(.*\)\.\.\.HEAD$|\1|p" $change_file)
+    all_needed_tags=$(get_needed_tags "$latest_git_tag" "$latest_log_tag")
+
+    [ ! "$all_needed_tags" ] && { echo "no new versions to add"; return 1; }
+
+    IFS="$nl"
+    for needed_tag in $all_needed_tags; do
+        update_diffs "$latest_git_tag" "$latest_log_tag" "$needed_tag"
+        update_links "$latest_log_tag" "$needed_tag"
+        echo "added $needed_tag to $change_file"
+
+        latest_log_tag="$needed_tag"
+    done
+}
+
+Run_all() {
     save_file=$(cat $change_file)
-    ! modify_file  && return 1
+    ! Update_changelog && return 1
     first_change=$(stat -qf "%Sc" $change_file)
     ${EDITOR:-vi} $change_file
     last_change=$(stat -qf "%Sc" $change_file)
@@ -294,38 +372,21 @@ run_all() {
     git add $change_file &&
         git commit --quiet -m "docs: update changelog" &&
         git push --quiet origin &&
-        make_and_push_tag -p && post_release
+        Make_and_push_tag -p && Post_release
 }
 
-modify_file() {
-    ! startup_checks && return 1
+#### Args ####
 
-    latest_git_ver_name=$(get_versions -v | head -1)
-    latest_log_ver_name=$(sed -n "s|^\[Unreleased\]:.*/\(.*\)\.\.\.HEAD$|\1|p" $change_file)
-    needed_log_ver_names=$(get_needed_log_ver_names "$latest_git_ver_name" "$latest_log_ver_name")
-
-    [ ! "$needed_log_ver_names" ] && { echo "no new versions to add"; return 1; }
-
-    IFS="$nl"
-    for needed_log_ver_name in $needed_log_ver_names; do
-        update_diffs "$latest_git_ver_name" "$latest_log_ver_name" "$needed_log_ver_name"
-        update_links "$latest_log_ver_name" "$needed_log_ver_name"
-        echo "added $needed_log_ver_name to $change_file"
-
-        latest_log_ver_name="$needed_log_ver_name"
-    done
-}
-
-[ ! "$1"             ] && { modify_file;                  exit;   }
+[ ! "$1"             ] && { Update_changelog;             exit;   }
 [ "$3"               ] && { echo "too many argument" >&2; exit 1; }
-[ "$1" = "auth"      ] && { auth "$2";                    exit;   }
-[ "$1" = "post"      ] && { post_release "$2";            exit;   }
-[ "$1" = "tag"       ] && { make_and_push_tag "$2";       exit;   }
+[ "$1" = "auth"      ] && { Save_auth "$2";               exit;   }
+[ "$1" = "post"      ] && { Post_release "$2";            exit;   }
+[ "$1" = "tag"       ] && { Make_and_push_tag "$2";       exit;   }
 [ "$2"               ] && { echo "too many argument" >&2; exit 1; }
-[ "$1" = "init"      ] && { init;                         exit;   }
-[ "$1" = "all"       ] && { run_all;                      exit;   }
-[ "$1" = "-h"        ] && { usage;                        exit;   }
-[ "$1" = "help"      ] && { usage;                        exit;   }
-[ "$1" = "--help"    ] && { usage;                        exit;   }
+[ "$1" = "init"      ] && { Create_changelog;             exit;   }
+[ "$1" = "all"       ] && { Run_all;                      exit;   }
+[ "$1" = "-h"        ] && { Usage;                        exit;   }
+[ "$1" = "help"      ] && { Usage;                        exit;   }
+[ "$1" = "--help"    ] && { Usage;                        exit;   }
 [ "$1" = "--version" ] && { echo "$change_version";       exit;   }
-[ "$1" ] && { printf "couldn't recognize argument\n\n" >&2; usage >&2; exit 1; }
+[ "$1" ] && { printf "couldn't recognize argument\n\n" >&2; Usage >&2; exit 1; }
