fix: error handling and all command

diff --git a/change b/change
--- a/change
+++ b/change
@@ -77,8 +77,10 @@ get_needed_log_ver_names() {
     latest_git_ver_name=$1
     latest_log_ver_name=$2
 
-    git tag --list "[[:digit:]]*\.[[:digit:]]*" --sort="-v:refname" |
-        sed -n "/$latest_log_ver_name/!p;//q" | sed '1!G;h;$!d'
+    tags=$(git tag --list "[[:digit:]]*\.[[:digit:]]*" --sort="-v:refname")
+
+    ! echo "$tags" | grep -q "$latest_log_ver_name" && return 0
+    echo "$tags" | sed -n "/$latest_log_ver_name/!p;//q" | sed '1!G;h;$!d'
 
     latest_changes=$(git log --pretty=format:"%B" "$latest_git_ver_name..")
     [ ! "$latest_changes" ] && return
@@ -164,13 +166,13 @@ get_commits_between() {
 }
 
 startup_checks() {
-    ! git rev-parse 2> /dev/null && { echo "you're no in a git repo" >&2; exit 1; }
-    [ ! -e "$change_file" ] && { echo "couldn't find $change_file" >&2; exit 1; }
+    ! git rev-parse 2> /dev/null && { echo "you're no in a git repo" >&2; return 1; }
+    [ ! -e "$change_file" ] && { echo "couldn't find $change_file" >&2; return 1; }
     return 0
 }
 
 make_and_push_tag() {
-    ! startup_checks && exit 1
+    ! startup_checks && return 1
 
     latest_log_ver_name=$(sed -n "s|^\[Unreleased\]:.*/\(.*\)\.\.\.HEAD$|\1|p" $change_file)
 
@@ -185,14 +187,14 @@ auth() {
     printf "token: "
     read -r token
 
-    [ ! "$token" ] && { echo "invalid token" >&2; exit 1; }
+    [ ! "$token" ] && { echo "invalid token" >&2; return 1; }
     [ ! -d "$auth_dir" ] && mkdir -p "$auth_dir"
     echo "$token" | base64 > "$auth_file" && echo "done"
 }
 
 post_release() {
-    ! startup_checks && exit 1
-    [ ! -e "$auth_file" ] && { echo "you need to save a token with the auth" >&2; exit 1; }
+    ! startup_checks && return 1
+    [ ! -e "$auth_file" ] && { echo "you need to save a token with the auth" >&2; return 1; }
 
     auth_token=$(base64 -D < "$auth_file")
     latest_log_ver_name=$(sed -n "s|^\[Unreleased\]:.*/\(.*\)\.\.\.HEAD$|\1|p" $change_file)
@@ -212,15 +214,15 @@ post_release() {
 }
 
 init() {
-    ! git rev-parse 2> /dev/null && { echo "you're no in a git repo" >&2; exit 1; }
+    ! git rev-parse 2> /dev/null && { echo "you're no in a git repo" >&2; return 1; }
 
     first_ver_name=$(git tag --list "[[:digit:]]*\.[[:digit:]]*" --sort="v:refname" | head -1)
     first_ver=$(get_version "$first_ver_name")
     first_commits=$(git log --pretty=format:"%s" "$first_ver_name")
     repo_url=$(git config --get remote.origin.url | sed "s|\(.*\)\.git|\1|")
 
-    [ -e "$change_file" ] && { echo "$change_file already exists" >&2; exit 1; }
-    [ ! "$first_ver" ] && { echo "couldn't get first version" >&2; exit 2; }
+    [ -e "$change_file" ] && { echo "$change_file already exists" >&2; return 1; }
+    [ ! "$first_ver" ] && { echo "couldn't get first version" >&2; return 2; }
 
     echo "# Changelog
 All notable changes to this project will be documented in this file.
@@ -236,29 +238,29 @@ $(format_commits "$first_commits")
 [Unreleased]: $repo_url/compare/$first_ver_name...HEAD
 [$first_ver]: $repo_url/releases/tag/$first_ver_name" > "$change_file"
 
-    [ ! -e "$change_file" ] && echo "something when wrong while creating $change_file" >&2 && exit 1
+    [ ! -e "$change_file" ] &&
+        echo "something when wrong while creating $change_file" >&2 && return 1
     echo "created $change_file" >&2
 }
 
 run_all() {
-    change_file || exit 1
+    change_file
     first_change=$(stat -qf "%Sc" $change_file)
     ${EDITOR:-vi} $change_file
     last_change=$(stat -qf "%Sc" $change_file)
     [ "$first_change" = "$last_change" ] &&
-        echo "cancelling because no manual edits were made to $change_file" >&2 &&
-        exit 1
-    git add $change_file && git commit --amend && make_and_push_tag && post_release
+        echo "cancelling because no manual edits were made to $change_file" >&2 && return 1
+    git add $change_file && git commit --amend --no-edit && make_and_push_tag && post_release
 }
 
 change_file() {
-    ! startup_checks && exit 1
+    ! startup_checks && return 1
 
     latest_git_ver_name=$(git tag --list "[[:digit:]]*\.[[:digit:]]*" --sort="-v:refname" | head -1)
     latest_log_ver_name=$(sed -n "s|^\[Unreleased\]:.*/\(.*\)\.\.\.HEAD$|\1|p" $change_file)
     needed_log_ver_names=$(get_needed_log_ver_names "$latest_git_ver_name" "$latest_log_ver_name")
 
-    [ ! "$needed_log_ver_names" ] && { echo "no new versions to add" >&2; exit 0; }
+    [ ! "$needed_log_ver_names" ] && { echo "no new versions to add" >&2; return 1; }
 
     IFS="$nl"
     for needed_log_ver_name in $needed_log_ver_names; do
