refactor functions

diff --git a/change b/change
--- a/change
+++ b/change
@@ -55,22 +55,33 @@ semver_git_tags() {
     git tag --list --sort='-v:refname' | filter_semver
 }
 
-inc_tag_major() {
+tag_exists() {
     tag=$1
-    major=$(echo "$tag" | semver_select '\2')
-    echo "$tag" | semver_select "\1$((major + 1)).0.0\5\9"
+    semver_git_tags | grep -q "^$tag$" && return
+    return 1
 }
 
-inc_tag_minor() {
-    tag=$1
-    minor=$(echo "$tag" | semver_select '\3')
-    echo "$tag" | semver_select "\1\2.$((minor + 1)).0\5\9"
+latest_inc_major() {
+    latest=$(semver_git_tags | head -1)
+    major=$(echo "$latest" | semver_select '\2')
+    echo "$latest" | semver_select "\1$((major + 1)).0.0\5\9"
 }
 
-inc_tag_patch() {
+latest_inc_minor() {
+    latest=$(semver_git_tags | head -1)
+    minor=$(echo "$latest" | semver_select '\3')
+    echo "$latest" | semver_select "\1\2.$((minor + 1)).0\5\9"
+}
+
+latest_inc_patch() {
+    latest=$(semver_git_tags | head -1)
+    patch=$(echo "$latest" | semver_select '\4')
+    echo "$latest" | semver_select "\1\2.\3.$((patch + 1))\5\9"
+}
+
+trim_tag() {
     tag=$1
-    patch=$(echo "$tag" | semver_select '\4')
-    echo "$tag" | semver_select "\1\2.\3.$((patch + 1))\5\9"
+    echo "$tag" | semver_select '\2.\3.\4'
 }
 
 rm_tag_suffix() {
@@ -89,7 +100,7 @@ tag_date_or_today() {
     date +%F
 }
 
-latest_log_tag() {
+top_log_tag() {
     sed -En 's,^\[Unreleased\]:.*/(.*)\.\.\.HEAD$,\1,p' $log_file
 }
 
@@ -104,16 +115,16 @@ remote_url_clean() {
         -e 's,\.git$,,' \
         -e 's,^https://.*@(.*),https://\1,' \
         -e 's,^git@(.*):(.*),https://\1/\2,'
-
 }
 
 #### Commits ####
 
-filter_major_commits() {
-    args="-e" # send arg "-v" for inverse and "-q" for quiet
-    [ "$1" ] && args="${1}e"
+# TODO: refine regex
+grep_commits_major() {
+    flags="-e" # use '-v' for inverse or '-q' for quiet
+    [ "$1" ] && flags="${1}e"
 
-    grep "$args" "^[A-Za-z]*!: " \
+    grep "$flags" "^[A-Za-z]*!: " \
         -e "^[A-Za-z]*(.*)!: " \
         -e "^[*-] *[A-Za-z]*!: " \
         -e "^[*-] *[A-Za-z]*(.*)!: " \
@@ -122,26 +133,29 @@ filter_major_commits() {
         -e "^BREAKING[ -]CHANGE"
 }
 
-filter_minor_commits() {
-    args="-e" # send arg "-v" for inverse and "-q" for quiet
-    [ "$1" ] && args="${1}e"
+# TODO: refine regex
+grep_commits_minor() {
+    flags="-e" # use '-v' for inverse or '-q' for quiet
+    [ "$1" ] && flags="${1}e"
 
-    grep -i "$args" "^feat: " \
+    grep -i "$flags" "^feat: " \
         -e "^feat(.*): " \
         -e "^[*-] *feat: " \
         -e "^[*-] *feat(.*): "
 }
 
-filter_patch_commits() {
-    args="-e" # send arg "-v" for inverse and "-q" for quiet
-    [ "$1" ] && args="${1}e"
+# TODO: refine regex
+grep_commits_patch() {
+    flags="-e" # use '-v' for inverse or '-q' for quiet
+    [ "$1" ] && flags="${1}e"
 
-    grep -i "$args" "^fix: " \
+    grep -i "$flags" "^fix: " \
         -e "^fix(.*): " \
         -e "^[*-] *fix: " \
         -e "^[*-] *fix(.*): "
 }
 
+# TODO: refine regex
 filter_conv_commits() {
     grep -e "^[A-Za-z]*: " -e "^[A-Za-z]*(.*): " \
         -e "^[*-] *[A-Za-z]*: " -e "^[*-] *[A-Za-z]*(.*): " \
@@ -151,6 +165,8 @@ filter_conv_commits() {
         -e "^BREAKING[ -]CHANGE"
 }
 
+# TODO: refine regex
+# TODO: reconsider use of sed
 fmt_conv_type() {
     sed -e "s|^[A-Za-z]*: \(.*$\)|\1|g" \
         -e "s|^[A-Za-z]*(\(.*\)): \(.*$\)|\2 for \1|g" \
@@ -165,56 +181,50 @@ fmt_conv_type() {
         -e "s|^BREAKING[ -]CHANGE|a breaking change|g"
 }
 
-# TODO: remove var from sed expression
 fmt_commits() {
     while read -r commit; do
-        first_char=$(echo "$commit" | cut -c1 | tr '[:lower:]' '[:upper:]')
-        echo "$commit" | sed -e "s,^.\(.*$\),- $first_char\1," -e 's,\(.*[^.!?]\)$,\1.,'
+        char=$(echo "$commit" | cut -c1 | tr '[:lower:]' '[:upper:]')
+        rest=$(echo "$commit" | cut -c2- | sed -E 's,(.*[^.!?])$,\1.,')
+        echo "- $char$rest"
     done
-
     printf '\n'
 }
 
-commits_between() {
-    log_format=$1
-    latest_git_tag=$2
-    latest_log_tag=$3
-    needed_tag=$4
+next_commit_range() {
+    next_tag=$1
 
-    highest_tag=$(printf '%s\n%s\n' "$latest_git_tag" "$needed_tag" | sort -Vr | head -1)
+    top_tag=$(top_log_tag)
+    range="$top_tag.."
+    tag_exists "$next_tag" && range="$top_tag..$next_tag"
 
-    tag_range="$latest_log_tag.."
-    [ "$latest_git_tag" = "$highest_tag" ] && tag_range="$latest_log_tag..$needed_tag"
-
-    # git log --pretty=format:"$log_format" "$tag_range" | sed "s|^M$||"
-    git log --pretty=format:"$log_format" "$tag_range" | sed "s|\r$||"
+    echo "$range"
 }
 
 #### Utils ####
 
-new_tag() {
+calc_new_tag() {
     latest_changes=$1
-    latest_git_tag=$2
 
-    echo "$latest_changes" | filter_major_commits -q && inc_tag_major "$latest_git_tag" && return
-    echo "$latest_changes" | filter_minor_commits -q && inc_tag_minor "$latest_git_tag" && return
-    echo "$latest_changes" | filter_patch_commits -q && inc_tag_patch "$latest_git_tag" && return
+    echo "$latest_changes" | grep_commits_major -q && latest_inc_major && return
+    echo "$latest_changes" | grep_commits_minor -q && latest_inc_minor && return
+    echo "$latest_changes" | grep_commits_patch -q && latest_inc_patch && return
 }
 
 format_commits() {
-    commits_head=$1
-    commits_body=$(echo "$2" | filter_conv_commits)
+    commit_range=$1
 
-    list=$(printf "%s\n%s" "$commits_head" "$commits_body")
+    sub=$(git log --pretty=format:"%s" "$commit_range")
+    bod=$(git log --pretty=format:"%b" "$commit_range" | filter_conv_commits)
+    list=$(printf '%s\n%s' "$sub" "$bod")
 
-    dep=$(echo "$list" | filter_major_commits)
-    list=$(echo "$list" | filter_major_commits -v)
+    dep=$(echo "$list" | grep_commits_major)
+    list=$(echo "$list" | grep_commits_major -v)
 
-    feat=$(echo "$list" | filter_minor_commits)
-    list=$(echo "$list" | filter_minor_commits -v)
+    feat=$(echo "$list" | grep_commits_minor)
+    list=$(echo "$list" | grep_commits_minor -v)
 
-    fix=$(echo "$list" | filter_patch_commits)
-    list=$(echo "$list" | filter_patch_commits -v)
+    fix=$(echo "$list" | grep_commits_patch)
+    list=$(echo "$list" | grep_commits_patch -v)
 
     [ "$dep" ] && echo "### BREAKING CHANGE" && echo "$dep" | fmt_conv_type | fmt_commits
     [ "$feat" ] && echo "### Added" && echo "$feat" | fmt_conv_type | fmt_commits
@@ -222,61 +232,16 @@ format_commits() {
     [ "$list" ] && echo "### Changed" && echo "$list" | fmt_conv_type | fmt_commits
 }
 
-# TODO: remove var from sed expression
-needed_tags() {
-    latest_git_tag=$1
-    latest_log_tag=$2
+# TODO: fix suffix handling
+unlogged_tags() {
+    top_tag=$(top_log_tag)
+    tag_exists "$top_tag" || return 0
+    semver_git_tags | sed -n "/^$top_tag$/q;p" | sort -V
 
-    tags=$(semver_git_tags)
-
-    echo "$tags" | grep -q "^${latest_log_tag}$" || return 0
-    echo "$tags" | sed -n "/^${latest_log_tag}$/!p;//q" | sed '1!G;h;$!d'
-
-    latest_changes=$(git log --pretty=format:"%B" "$latest_git_tag..")
-    [ ! "$latest_changes" ] && return
-
-    new_tag "$latest_changes" "$latest_git_tag" | rm_tag_suffix
-}
-
-# TODO: remove var from sed expression
-update_diffs() {
-    latest_git_tag=$1
-    latest_log_tag=$2
-    needed_tag=$3
-
-    latest_log_ver=$(rm_tag_prefix "$latest_log_tag")
-    needed_ver=$(rm_tag_prefix "$needed_tag")
-
-    new_commits_head=$(commits_between "%s" "$latest_git_tag" "$latest_log_tag" "$needed_tag")
-    new_commits_body=$(commits_between "%b" "$latest_git_tag" "$latest_log_tag" "$needed_tag")
-
-    new_section="## [$needed_ver] - $(tag_date_or_today "$needed_tag")\\
-$(format_commits "$new_commits_head" "$new_commits_body" | sed -e "s|\([&\\]\)|\\\\\1|g" -e "s|$|\\\\|")"
-
-    nl="
-"
-    regex="s|\(^## \[$latest_log_ver\] -.*$\)|$new_section$nl\1|"
-    sed -i.backup "$regex" $log_file && rm "$log_file.backup"
-}
-
-# TODO: remove var from sed expression
-update_links() {
-    latest_log_tag=$1
-    needed_tag=$2
-
-    latest_log_ver=$(rm_tag_prefix "$latest_log_tag")
-    needed_ver=$(rm_tag_prefix "$needed_tag")
-    repo_url=$(remote_url_clean)
-
-    new_link="[$needed_ver]: $repo_url/compare/$latest_log_tag...$needed_tag"
-
-    nl="
-"
-    regex="s|\(^\[$latest_log_ver\]:.*$\)|$new_link\\$nl\1|"
-    sed -i.backup "$regex" $log_file && rm "$log_file.backup"
-
-    regex="s|\(^\[Unreleased\]:.*\)/$latest_log_tag\.\.\.HEAD$|\1/$needed_tag...HEAD|"
-    sed -i.backup "$regex" $log_file && rm "$log_file.backup"
+    latest_tag=$(semver_git_tags | head -1)
+    unlogged_commits=$(git log --pretty=format:"%B" "$latest_tag..")
+    [ ! "$unlogged_commits" ] && return
+    calc_new_tag "$unlogged_commits" | rm_tag_suffix
 }
 
 startup_checks() {
@@ -288,85 +253,20 @@ startup_checks() {
 
 bump_version() {
     [ ! "$bump_script" ] && return
-    latest_log_tag=$(latest_log_tag)
+    [ ! -f "$bump_script" ] && echo "script not found: $bump_script" >&2 && return 1
 
+    top_tag=$(top_log_tag)
     [ -x "$bump_script" ] &&
-        echo "executing $bump_script $latest_log_tag" && "$bump_script" "$latest_log_tag" && return
-
-    [ ! -x "$bump_script" ] && [ -f "$bump_script" ] &&
-        echo "executing sh $bump_script $latest_log_tag" && sh "$bump_script" "$latest_log_tag" && return
-
-    [ ! -f "$bump_script" ] &&
-        echo "script not found: $bump_script" >&2 && return 1
+        echo "executing $bump_script $top_tag" && "$bump_script" "$top_tag"
+    [ ! -x "$bump_script" ] &&
+        echo "executing sh $bump_script $top_tag" && sh "$bump_script" "$top_tag"
 }
 
-#### Public ####
+initial_log() {
+    oldest_tag=$1
 
-tag_and_push() {
-    startup_checks || return 1
-    latest_log_tag=$(latest_log_tag)
-    repo_url=$(remote_url)
-
-    git tag "$latest_log_tag" || return 1
-    echo "tagged latest commit as $latest_log_tag"
-
-    [ "$push_tag" = "true" ] &&
-        git push --quiet "$repo_url" "$latest_log_tag" &&
-        echo "pushed $latest_log_tag to $repo_url" &&
-        return 0
-
-    printf "to push the latest tag use:\n\tgit push %s %s\n" "$repo_url" "$latest_log_tag"
-    printf "to push all local tags use:\n\tgit push %s --tags\n" "$repo_url"
-}
-
-save_auth() {
-    [ ! "$token" ] && echo "enter a personal access token" && printf "token: " && read -r token
-    [ ! "$token" ] && echo "invalid token" >&2 && return 1
-    [ ! -d "$auth_dir" ] && mkdir -p "$auth_dir"
-
-    echo "$token" | base64 >"$auth_file" && echo "git auth saved"
-}
-
-post_release() {
-    startup_checks || return 1
-    [ ! -e "$auth_file" ] && echo "you need to save a token with the auth" >&2 && return 1
-
-    auth_token=$(base64 --decode <"$auth_file")
-    latest_log_tag=$(latest_log_tag)
-    latest_log_ver=$(rm_tag_prefix "$latest_log_tag")
-    # TODO: create function for this
-    repo_url=$(remote_url_clean | sed "s|\(^.*\)\(github.com\)|\1api.\2/repos|")
-
-    diff=$(sed -n "/^## \[$latest_log_ver\] -.*/,/^## \[.*\] -.*/P" $log_file | sed "\$d")
-    link=$(grep "^\[$latest_log_ver\]: .*" $log_file)
-    # body=$(echo "$diff$nl$nl$link" | sed -e "s|\([\"\\]\)|\\\\\1|g" -e "s|$|\\\\|" | tr '\n' 'n')
-    body=$(printf '%s\n\n%s\n' "$diff" "$link" | sed -e "s|\([\"\\]\)|\\\\\1|g" -e "s|$|\\\\|" | tr '\n' 'n')
-
-    [ "$dry_run" = "true" ] &&
-        printf "%s\n%s\n%s\n" "$repo_url" "$latest_log_tag" "$body" && return
-
-    # TODO: improve escaping
-    curl -X POST "$repo_url/releases" \
-        -H "Authorization: token $auth_token" \
-        -H "Content-Type: application/json" \
-        -d "{\"tag_name\": \"$latest_log_tag\", \"name\": \"$latest_log_tag\", \"body\": \"$body\" }"
-}
-
-create_log() {
-    [ ! -d .git ] && echo "the current directory doesn't contain .git" >&2 && return 1
-    [ -e $log_file ] && echo "$log_file already exists" >&2 && return 1
-
-    first_tag=$(semver_git_tags | tail -n 1)
-    [ ! "$first_tag" ] && echo "couldn't find any valid version tags" >&2 && return 2
-
-    first_ver=$(rm_tag_prefix "$first_tag")
-    [ ! "$first_ver" ] && echo "couldn't get first version" >&2 && return 2
-
-    first_commits=$(git log --pretty=format:"%s" "$first_tag")
-    [ ! "$first_commits" ] && echo "couldn't get first commits" >&2 && return 2
-
-    repo_url=$(remote_url_clean)
-    [ ! "$repo_url" ] && echo "remote url isn't set for this repo" >&2 && return 1
+    oldest_ver=$(rm_tag_prefix "$oldest_tag")
+    date=$(tag_date_or_today "$oldest_tag")
 
     echo "# Changelog
 All notable changes to this project will be documented in this file.
@@ -376,58 +276,142 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ## [Unreleased]
 
-## [$first_ver] - $(tag_date_or_today "$first_tag")
-$(format_commits "$first_commits")
+## [$oldest_ver] - $date"
 
-[Unreleased]: $repo_url/compare/$first_tag...HEAD
-[$first_ver]: $repo_url/releases/tag/$first_tag" >$log_file
+    format_commits "$oldest_tag"
 
-    [ ! -s $log_file ] &&
-        echo "something went wrong while creating $log_file" >&2 && return 1
+    echo "[Unreleased]: $repo_url/compare/$oldest_tag...HEAD
+[$oldest_ver]: $repo_url/releases/tag/$oldest_tag"
+}
+
+# TODO: handle prefix and suffix trimming
+add_to_log() {
+    next_tag=$1
+
+    top_tag=$(top_log_tag)
+    top_ver=$(rm_tag_prefix "$top_tag")
+    next_ver=$(rm_tag_prefix "$next_tag")
+    date=$(tag_date_or_today "$next_tag")
+    repo_url=$(remote_url_clean)
+    commit_range=$(next_commit_range "$next_tag")
+
+    sed -n "/^## \[$top_ver\] - [1-9][0-9-]*$/q;p" $log_file
+    echo "## [$next_ver] - $date"
+    format_commits "$commit_range"
+    sed -n "/^## \[$top_ver\] - [1-9][0-9-]*$/,/^\[Unreleased\]: https:[^ ]*$/p;" $log_file |
+        sed '$d'
+    echo "[Unreleased]: $repo_url/compare/$next_tag...HEAD"
+    echo "[$next_ver]: $repo_url/compare/$top_tag...$next_tag"
+    sed -n "/^\[$top_ver\]: https:[^ ]*$/,\$p" $log_file
+}
+
+#### Commands ####
+
+tag_command() {
+    startup_checks || return 1
+    top_tag=$(top_log_tag)
+    repo_url=$(remote_url)
+
+    git tag "$top_tag" || return 1
+    echo "tagged latest commit as $top_tag"
+
+    [ "$push_tag" ] &&
+        git push --quiet "$repo_url" "$top_tag" && echo "pushed $top_tag to $repo_url" && return
+
+    printf "to push the latest tag use:\n\tgit push %s %s\n" "$repo_url" "$top_tag"
+    printf "to push all local tags use:\n\tgit push %s --tags\n" "$repo_url"
+}
+
+auth_command() {
+    [ ! "$token" ] && echo "enter a personal access token" && printf "token: " && read -r token
+    [ ! "$token" ] && echo "invalid token" >&2 && return 1
+    [ ! -d "$auth_dir" ] && mkdir -p "$auth_dir"
+    echo "$token" | base64 >"$auth_file" && echo "git auth saved"
+}
+
+# TODO: test
+post_command() {
+    startup_checks || return 1
+    [ ! -e "$auth_file" ] && echo "you need to save a token with the auth" >&2 && return 1
+
+    auth_token=$(<"$auth_file" base64 --decode)
+    top_tag=$(top_log_tag)
+    top_ver=$(rm_tag_prefix "$top_tag")
+    api_url=$(remote_url_clean | sed -E "s|^(.*)(github.com)|\1api.\2/repos|")
+
+    link=$(grep "^\[$top_ver\]: https:[^ ]*$" $log_file)
+    entry=$(sed -n "/^## \[$top_ver\] - [1-9][0-9-]*$/,/^## \[..*\] - [1-9][0-9-]*$/p" $log_file |
+        sed '$d')
+
+    # body=$(printf '%s\n\n%s\n' "$entry" "$link")
+    body=$(printf '%s\n\n%s\n' "$entry" "$link" |
+        sed -E -e "s,([\"\\]),\\\\\1,g" -e "s,$,\\\\," | tr '\n' 'n')
+
+    [ "$dry_run" ] && printf "%s\n%s\n%s\n" "$api_url" "$top_tag" "$body" && return
+
+    # data=$(printf '{"tag_name": "%s", "name": "%s", "body": "%s"}' "$top_tag" "$top_tag" "$body")
+
+    curl -X POST "$api_url/releases" \
+        -H "Authorization: token $auth_token" \
+        -H "Content-Type: application/json" \
+        -d "{\"tag_name\": \"$top_tag\", \"name\": \"$top_tag\", \"body\": \"$body\" }"
+        # --data-urlencode "=$data"
+}
+
+init_command() {
+    [ ! -d .git ] && echo "the current directory doesn't contain .git" >&2 && return 1
+    [ -e $log_file ] && echo "$log_file already exists" >&2 && return 1
+
+    oldest_tag=$(semver_git_tags | tail -n 1)
+    [ ! "$oldest_tag" ] && echo "couldn't find any valid version tags" >&2 && return 2
+
+    repo_url=$(remote_url_clean)
+    [ ! "$repo_url" ] && echo "remote url isn't set for this repo" >&2 && return 1
+
+    initial_log "$oldest_tag" >$log_file
+
+    [ ! -s $log_file ] && echo "something went wrong while creating $log_file" >&2 && return 1
     echo "created $log_file"
 }
 
-update_log() {
+update_command() {
     startup_checks || return 1
+    tags=$(unlogged_tags)
+    [ ! "$tags" ] && echo "no new versions to add" && return 1
 
-    latest_git_tag=$(semver_git_tags | head -1)
-    latest_log_tag=$(latest_log_tag)
-    all_needed_tags=$(needed_tags "$latest_git_tag" "$latest_log_tag")
+    echo "$tags" | while read -r next_tag; do
+        new_log=$(add_to_log "$next_tag")
+        echo "$new_log" >$log_file
 
-    [ ! "$all_needed_tags" ] && echo "no new versions to add" && return 1
-
-    echo "$all_needed_tags" | while read -r needed_tag; do
-        update_diffs "$latest_git_tag" "$latest_log_tag" "$needed_tag"
-        update_links "$latest_log_tag" "$needed_tag"
-        echo "added $needed_tag to $log_file"
-
-        latest_log_tag="$needed_tag"
+        echo "added $next_tag to $log_file"
     done
 
     [ "$command" ] && return 0
     bump_version
 }
 
-run_all() {
-    save_file=$(cat $log_file)
-    update_log || return 1
-    first_change=$(stat -qf "%Sc" $log_file)
+# TODO: refactor
+all_command() {
+    backup=$(cat $log_file)
+    update_command || return 1
+
+    last_changed=$(stat -qf "%Sc" $log_file)
     ${EDITOR:-vi} $log_file
-    last_change=$(stat -qf "%Sc" $log_file)
-    [ "$first_change" = "$last_change" ] &&
+    [ $(stat -qf "%Sc" $log_file) = $last_changed ] &&
         echo "cancelling because no manual edits were made to $log_file" >&2 &&
-        echo "$save_file" >$log_file &&
+        echo "$backup" >$log_file &&
         return 1
+
     bump_version
     push_tag="true"
     git add $log_file &&
-        git commit --quiet -m "docs: update changelog" &&
-        git push --quiet &&
-        tag_and_push && post_release
+        git commit --quiet -m "docs: update changelog" && git push --quiet &&
+        tag_and_push && post_command
 }
 
 #### Args ####
 
+# TODO: refactor
 command=$1
 [ "$(expr "$command" : '-.*')" != 0 ] && command=''
 [ "$command" ] && shift
@@ -449,12 +433,12 @@ while [ $# != 0 ]; do
 done
 
 case $command in
-'') update_log ;;
-'init') create_log ;;
-'auth') save_auth ;;
-'tag') tag_and_push ;;
-'post') post_release ;;
-'all') run_all ;;
+'') update_command ;;
+'init') init_command ;;
+'auth') auth_command ;;
+'tag') tag_command ;;
+'post') post_command ;;
+'all') all_command ;;
 'help') usage ;;
 'version') echo "$version" ;;
 *) echo "invalid command: $command" >&2 && exit 1 ;;
